#!/bin/bash

#v1.0

REPLACE=1 # 1 is False
QUALITY=70
HEIGHT=1920

usage="$(cat <<-EOF
Example :
$(basename "$0")

By default, it saves smallified comics in 'Smaller_comics' default folder.

$(basename "$0") -r or $(basename "$0") --replace
will REPLACE your comics ! Be careful !!

$(basename "$0") -f \"my smaller comics\"
will save your smallified comics in \"my smaller comics\"

$(basename "$0") [-h] [-r] [-f folder]
where:
    -h              show this help text
    -r, --replace   set the 'Replace' flag on ! It replace your comics !
                    Be very careful with this
    -f, --folder    set the folder where to save smallified comics
    -q, --quality   set the jpeg quality (0 to 100, default is 70)
    -s, --size      set the new image height (default is 1920)
EOF
)"

while :; do
    case $1 in
        -h|-\?|--help)
            #show_help    # Display a usage synopsis.
            echo "$usage"
            exit
            ;;
        -q|--quality)       # Takes an option argument; ensure it has been specified.
            if [ "$2" ]; then
                QUALITY="$2"
                echo "Jpeg quality : '$QUALITY'"
                shift
            else
                die 'ERROR: "--quality" requires a non-empty option argument.'
            fi
            ;;
        -s|--size)       # Takes an option argument; ensure it has been specified.
            if [ "$2" ]; then
                HEIGHT="$2"
                echo "Image new height : '$HEIGHT'"
                shift
            else
                die 'ERROR: "--height" requires a non-empty option argument.'
            fi
            ;;
        -r|--replace)       # Takes an option argument; ensure it has been specified.
            REPLACE=0
            ;;
        -f|--folder)       # Takes an option argument; ensure it has been specified.
            if [ "$2" ]; then
                FOLDER="$2"
                # echo "Destination folder : '$FOLDER'"
                shift
            else
                die 'ERROR: "--folder" requires a non-empty option argument.'
            fi
            ;;
        --)              # End of all options.
            shift
            break
            ;;
        -?*)
            printf 'WARN: Unknown option (ignored): %s\n' "$1" >&2
            ;;
        *)               # Default case: No more options, so break out of the loop.
            break
    esac

    shift
done

for FILE in *{.cbr,.CBR,.cbz,.CBZ}
do
    # echo "smallify $FILE 70 1920 $params"
    # second argument is jpeg quality
    # third argument is the new height of pictures
    [ -e "$FILE" ] || continue
    # Stupid mode, because folder is finally deleted in replace mode
    if [[ $REPLACE -eq 0 && ! -z "$FOLDER" ]]; then
        smallify "$FILE" "$QUALITY" "$HEIGHT" -r -f "$FOLDER"
    # Replace mode, -r option
    elif [[ $REPLACE -eq 0 ]]; then
        smallify "$FILE" "$QUALITY" "$HEIGHT" -r
    # No Replace mode, with custom folder
    elif [ ! -z "$FOLDER" ]; then
        smallify "$FILE" "$QUALITY" "$HEIGHT" -f "$FOLDER"
    # Default mode, no replace
    else
        smallify "$FILE" "$QUALITY" "$HEIGHT"
    fi
    echo "------------------------"
done
